pipeline {
    agent any

    stages {

        stage('Environment Check') {
            steps {
                bat 'java -version'
                bat 'python --version'
            }
        }

        stage('Verify JMeter Files') {
            steps {
                bat 'dir jmeter'
                bat 'dir jmeter\\tests'
            }
        }

        stage('Run JMeter Test') {
            steps {
                bat """
                C:\\JMeter\\apache-jmeter-5.6.3\\apache-jmeter-5.6.3\\bin\\jmeter.bat ^
                -n ^
                -t jmeter\\tests\\test-plan.jmx ^
                -l results.jtl ^
                -JinfluxdbMetricsSender=org.apache.jmeter.visualizers.backend.influxdb.HttpMetricsSender ^
                -JinfluxdbUrl=http://localhost:8086/write?db=jmeter ^
                -Japplication=perf-eng-framework ^
                -Jmeasurement=jmeter ^
                -JsummaryOnly=false ^
                -JsamplersRegex=.* ^
                -Jpercentiles=90;95;99 ^
                -JtestTitle=jenkins-jmeter-test ^
                -JinfluxdbDatabase=jmeter ^
                -Jjmeter.save.saveservice.autoflush=true ^
                -e -f -o reports
                """
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'results.jtl, reports/**', allowEmptyArchive: true
        }
    }
}
