pipeline {
    agent any

    stages {

        stage('Environment Check') {
            steps {
                bat 'java -version'
                bat 'python --version'
            }
        }

        stage('Verify JMeter Files') {
            steps {
                bat 'dir jmeter'
                bat 'dir jmeter\\tests'
            }
        }

        stage('Run JMeter Test') {
            steps {
                bat '''
                C:\\JMeter\\apache-jmeter-5.6.3\\apache-jmeter-5.6.3\\bin\\jmeter.bat ^
                -n ^
                -t jmeter\\tests\\test-plan.jmx ^
                -l results.jtl ^
                -e -f -o reports
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'results.jtl, reports/**', allowEmptyArchive: true
        }
    }
}
